package com.jitelecom.productadviser.ui.screens

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import com.jitelecom.productadviser.data.local.*
import com.jitelecom.productadviser.data.repository.toDomain
import com.jitelecom.productadviser.domain.model.*
import com.jitelecom.productadviser.ui.*
import kotlinx.coroutines.launch

@Composable
fun SettingsScreen(viewModel:SettingsViewModel=hiltViewModel()){
    val settings by viewModel.settings.collectAsState();var remote by remember(settings.remoteDatabaseUrl){mutableStateOf(settings.remoteDatabaseUrl)}
    LazyColumn(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){
        item{ScreenHeader("Settings","Local preferences")}
        item{Card{Row(Modifier.fillMaxWidth().padding(16.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Dark mode",fontWeight=FontWeight.Bold);Text("Stored only on this device",style=MaterialTheme.typography.bodySmall)};Switch(settings.darkMode,viewModel::dark)}}}
        item{Card{Column(Modifier.padding(16.dp)){Text("Remote database manifest",fontWeight=FontWeight.Bold);Text("Optional. The app remains fully usable without it.",style=MaterialTheme.typography.bodySmall);Spacer(Modifier.height(8.dp));OutlinedTextField(value=remote,onValueChange={remote=it},label={Text("HTTPS manifest URL")},modifier=Modifier.fillMaxWidth(),singleLine=true);Button(onClick={viewModel.remoteUrl(remote)},modifier=Modifier.align(Alignment.End)){Text("Save")}}}}
        item{Card{Column(Modifier.padding(16.dp)){Text("Above-budget allowance",fontWeight=FontWeight.Bold);Text("${settings.allowAboveBudgetPercent}% when the employee explicitly enables it",style=MaterialTheme.typography.bodySmall);Slider(value=settings.allowAboveBudgetPercent.toFloat(),onValueChange={viewModel.aboveBudget(it.toInt())},valueRange=0f..25f,steps=24)}}}
        item{NoticeCard("No API keys or sensitive credentials are stored or exported. Admin PIN protection is local convenience protection, not enterprise-grade security.")}
    }
}

@Composable
fun DatabaseInfoScreen(online:Boolean,onAdmin:()->Unit,viewModel:HomeViewModel=hiltViewModel()){
    val products by viewModel.products.collectAsState();val software by viewModel.software.collectAsState();val version by viewModel.databaseVersion.collectAsState()
    Column(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){ScreenHeader("Database","Local source of truth"){OnlineBadge(online)};Card{Column(Modifier.padding(18.dp)){InfoRow("Version",version?:"Loading…");InfoRow("Products",products.size.toString());InfoRow("Software",software.size.toString());InfoRow("Operation","Offline-first")}};NoticeCard("Remote checks are optional. Updates are validated, backed up, and committed in one transaction; failures roll back without replacing the current catalog.");Button(onClick=onAdmin,modifier=Modifier.fillMaxWidth()){Icon(Icons.Default.AdminPanelSettings,null);Spacer(Modifier.width(8.dp));Text("OPEN ADMIN / DATABASE")};if(!online)NoticeCard("Remote updates and official links are unavailable. Search, compatibility, recommendations, comparison and editing still work.")}
}

@Composable
fun AdminScreen(online:Boolean,viewModel:AdminViewModel=hiltViewModel()){
    val state by viewModel.state.collectAsState();if(!state.unlocked){AdminUnlock(state.message,viewModel::unlock);return}
    var tab by remember{mutableIntStateOf(0)};var showProduct by remember{mutableStateOf<ProductSpec?>(null)};var showProcessor by remember{mutableStateOf(false)};var showGpu by remember{mutableStateOf(false)};var showSoftware by remember{mutableStateOf(false)};var requirementFor by remember{mutableStateOf<SoftwareEntity?>(null)}
    val products by viewModel.productsFlow.collectAsState();val processors by viewModel.processors.collectAsState();val gpus by viewModel.gpus.collectAsState();val software by viewModel.software.collectAsState()
    Column(Modifier.fillMaxSize().padding(16.dp)){ScreenHeader("Admin / Database","Local PIN protection only"){IconButton(onClick=viewModel::lock){Icon(Icons.Default.Lock,"Lock")}};state.message?.let{Text(it,color=MaterialTheme.colorScheme.primary,style=MaterialTheme.typography.bodySmall)};ScrollableTabRow(selectedTabIndex=tab,edgePadding=0.dp){listOf("Products","Hardware","Software","Import & backup").forEachIndexed{i,label->Tab(selected=tab==i,onClick={tab=i},text={Text(label)})}};Spacer(Modifier.height(10.dp));when(tab){0->AdminProducts(products,{showProduct=emptyProduct()},{showProduct=it},viewModel::archiveProduct);1->AdminHardware(processors,gpus,{showProcessor=true},{showGpu=true});2->AdminSoftware(software,{showSoftware=true}){requirementFor=it};else->ImportBackupPane(online,state,viewModel)}}
    showProduct?.let{ProductEditor(it,processors,gpus,onDismiss={showProduct=null},onSave={viewModel.saveProduct(it);showProduct=null})};if(showProcessor)ProcessorEditor({showProcessor=false}){viewModel.saveProcessor(it);showProcessor=false};if(showGpu)GpuEditor({showGpu=false}){viewModel.saveGpu(it);showGpu=false};if(showSoftware)SoftwareEditor({showSoftware=false}){viewModel.saveSoftware(it);showSoftware=false};requirementFor?.let{app->RequirementEditor(app,{requirementFor=null}){viewModel.saveRequirement(it);requirementFor=null}}
}

@Composable private fun AdminUnlock(message:String?,unlock:(String)->Unit){var pin by remember{mutableStateOf("")};Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Card(Modifier.widthIn(max=420.dp).padding(20.dp)){Column(Modifier.padding(22.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.AdminPanelSettings,null,Modifier.size(48.dp));Text("Admin Mode",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Local protection — not enterprise security",style=MaterialTheme.typography.bodySmall);Spacer(Modifier.height(12.dp));OutlinedTextField(pin,{pin=it.filter(Char::isDigit)},label={Text("PIN")},visualTransformation=PasswordVisualTransformation(),singleLine=true);message?.let{Text(it,color=MaterialTheme.colorScheme.error)};Spacer(Modifier.height(10.dp));Button({unlock(pin)},Modifier.fillMaxWidth()){Text("UNLOCK")};Text("Development default PIN: 2468",style=MaterialTheme.typography.labelSmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}}

@Composable private fun AdminProducts(products:List<ProductSpec>,add:()->Unit,edit:(ProductSpec)->Unit,archive:(Long)->Unit){Column{Button(add,Modifier.fillMaxWidth()){Icon(Icons.Default.Add,null);Text(" Add product")};Spacer(Modifier.height(8.dp));LazyColumn(verticalArrangement=Arrangement.spacedBy(7.dp)){items(products,key={it.id}){p->OutlinedCard{Row(Modifier.fillMaxWidth().padding(12.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(p.displayName,fontWeight=FontWeight.Bold);Text(p.sku,style=MaterialTheme.typography.bodySmall)};IconButton({edit(p)}){Icon(Icons.Default.Edit,"Edit")};IconButton({archive(p.id)}){Icon(Icons.Default.Archive,"Archive")}}}}}}}
@Composable private fun AdminHardware(processors:List<ProcessorEntity>,gpus:List<GpuEntity>,addCpu:()->Unit,addGpu:()->Unit){LazyColumn(verticalArrangement=Arrangement.spacedBy(7.dp)){item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(addCpu,Modifier.weight(1f)){Text("Add CPU")};Button(addGpu,Modifier.weight(1f)){Text("Add GPU")}}};item{Text("Processors",fontWeight=FontWeight.Bold)};items(processors){Text("${it.manufacturer} ${it.model} • internal tier ${it.performanceTier?:"?"}",style=MaterialTheme.typography.bodySmall)};item{Text("Graphics",fontWeight=FontWeight.Bold)};items(gpus){Text("${it.manufacturer} ${it.model} • internal tier ${it.performanceTier?:"?"}",style=MaterialTheme.typography.bodySmall)}}}
@Composable private fun AdminSoftware(software:List<SoftwareEntity>,add:()->Unit,requirements:(SoftwareEntity)->Unit){LazyColumn(verticalArrangement=Arrangement.spacedBy(7.dp)){item{Button(add,Modifier.fillMaxWidth()){Icon(Icons.Default.Add,null);Text(" Add software")}};items(software){s->OutlinedCard{Column(Modifier.padding(12.dp)){Text("${s.name} ${s.version}",fontWeight=FontWeight.Bold);Text("${s.category} • ${s.platform}",style=MaterialTheme.typography.bodySmall);TextButton(onClick={requirements(s)}){Text("Add or update requirements")}}}}}}

@Composable private fun ImportBackupPane(online:Boolean,state:AdminUiState,viewModel:AdminViewModel){val context=LocalContext.current;val scope=rememberCoroutineScope();var exportBytes by remember{mutableStateOf<ByteArray?>(null)};val open=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri->uri?.let{context.contentResolver.openInputStream(it)?.use{stream->viewModel.previewImport(stream.readBytes(),it.lastPathSegment?:"database.json")}}};val create=rememberLauncherForActivityResult(ActivityResultContracts.CreateDocument("application/json")){uri->uri?.let{target->exportBytes?.let{bytes->context.contentResolver.openOutputStream(target)?.use{it.write(bytes)}}}};LazyColumn(verticalArrangement=Arrangement.spacedBy(9.dp)){item{Button({open.launch(arrayOf("application/json","application/zip","text/csv"))},Modifier.fillMaxWidth()){Icon(Icons.Default.FileOpen,null);Text(" Import JSON / ZIP package")}};state.preview?.let{preview->item{Card{Column(Modifier.padding(14.dp)){Text("Import preview",fontWeight=FontWeight.Bold);Text("${preview.productCount} products • ${preview.softwareCount} software • version ${preview.version?:"unknown"}");preview.errors.forEach{Text("Error: ${it.record}: ${it.message}",color=MaterialTheme.colorScheme.error,style=MaterialTheme.typography.bodySmall)};preview.warnings.take(5).forEach{Text("Warning: ${it.record}: ${it.message}",style=MaterialTheme.typography.bodySmall)};Button(viewModel::commitImport,enabled=preview.canImport,modifier=Modifier.fillMaxWidth()){Text("VALIDATE & IMPORT")}}}}};item{OutlinedButton({scope.launch{exportBytes=viewModel.exportBytes();create.launch("JI_PRODUCT_DATABASE_BACKUP.json")}},Modifier.fillMaxWidth()){Icon(Icons.Default.SaveAlt,null);Text(" Export backup")}};item{Button(viewModel::checkUpdate,enabled=online,modifier=Modifier.fillMaxWidth()){Icon(Icons.Default.SystemUpdate,null);Text(" Check remote update")}};item{NoticeCard("Every import is validated first. A local safety backup is created before the database is replaced, and the transaction rolls back automatically if any write fails.")};item{PinChange(viewModel::setPin)}}}
@Composable private fun PinChange(setPin:(String)->Unit){var pin by remember{mutableStateOf("")};OutlinedCard{Column(Modifier.padding(14.dp)){Text("Change admin PIN",fontWeight=FontWeight.Bold);OutlinedTextField(pin,{pin=it.filter(Char::isDigit)},label={Text("New PIN (4+ digits)")},visualTransformation=PasswordVisualTransformation(),singleLine=true,modifier=Modifier.fillMaxWidth());Button({setPin(pin)},enabled=pin.length>=4,modifier=Modifier.align(Alignment.End)){Text("Update PIN")}}}}

private fun emptyProduct()=ProductSpec(0,"","","",category=ProductCategory.LAPTOP,price=0.0)
@Composable private fun ProductEditor(initial:ProductSpec,cpus:List<ProcessorEntity>,gpus:List<GpuEntity>,onDismiss:()->Unit,onSave:(ProductSpec)->Unit){var sku by remember{mutableStateOf(initial.sku)};var brand by remember{mutableStateOf(initial.brand)};var model by remember{mutableStateOf(initial.model)};var price by remember{mutableStateOf(initial.price.takeIf{it>0}?.toString().orEmpty())};var ram by remember{mutableStateOf(initial.ramGB?.toString().orEmpty())};var storage by remember{mutableStateOf(initial.storageGB?.toString().orEmpty())};var cpu by remember{mutableStateOf(cpus.firstOrNull{it.id==initial.processor?.id}?:cpus.firstOrNull())};var gpu by remember{mutableStateOf(gpus.firstOrNull{it.id==initial.gpu?.id}?:gpus.firstOrNull())};AlertDialog(onDismissRequest=onDismiss,title={Text(if(initial.id==0L)"Add product" else "Edit product")},text={Column(Modifier.heightIn(max=520.dp)){listOf("SKU" to sku,"Brand" to brand,"Model" to model,"Price" to price,"RAM GB" to ram,"Storage GB" to storage).forEach{(label,value)->OutlinedTextField(value,{v->when(label){"SKU"->sku=v;"Brand"->brand=v;"Model"->model=v;"Price"->price=v;"RAM GB"->ram=v;else->storage=v}},label={Text(label)},singleLine=true,modifier=Modifier.fillMaxWidth())};Selector("Processor",cpus,cpu,{"${it.manufacturer} ${it.model}"}){cpu=it};Selector("GPU",gpus,gpu,{"${it.manufacturer} ${it.model}"}){gpu=it}}},confirmButton={Button({onSave(initial.copy(sku=sku.trim(),brand=brand.trim(),model=model.trim(),price=price.toDoubleOrNull()?:0.0,ramGB=ram.toIntOrNull(),storageGB=storage.toIntOrNull(),processor=cpu?.toDomain(),gpu=gpu?.toDomain(),verificationStatus=VerificationStatus.UNVERIFIED,lastUpdated=java.time.LocalDate.now().toString()))},enabled=sku.isNotBlank()&&brand.isNotBlank()&&model.isNotBlank()&&price.toDoubleOrNull()!=null){Text("Save")}},dismissButton={TextButton(onDismiss){Text("Cancel")}})}

@Composable private fun ProcessorEditor(onDismiss:()->Unit,onSave:(ProcessorEntity)->Unit){var maker by remember{mutableStateOf("")};var model by remember{mutableStateOf("")};var family by remember{mutableStateOf("")};var tier by remember{mutableStateOf("")};SimpleEditor("Add processor",onDismiss,{onSave(ProcessorEntity(manufacturer=maker,model=model,family=family,performanceTier=tier.toIntOrNull(),notes="Needs verification"))},maker,model,{maker=it},{model=it}){OutlinedTextField(family,{family=it},label={Text("Family")});OutlinedTextField(tier,{tier=it.filter(Char::isDigit)},label={Text("Internal tier 1–7")})}}
@Composable private fun GpuEditor(onDismiss:()->Unit,onSave:(GpuEntity)->Unit){var maker by remember{mutableStateOf("")};var model by remember{mutableStateOf("")};var tier by remember{mutableStateOf("")};SimpleEditor("Add GPU",onDismiss,{onSave(GpuEntity(manufacturer=maker,model=model,type=GpuType.INTEGRATED,performanceTier=tier.toIntOrNull(),notes="Needs verification"))},maker,model,{maker=it},{model=it}){OutlinedTextField(tier,{tier=it.filter(Char::isDigit)},label={Text("Internal tier 1–7")})}}
@Composable private fun SoftwareEditor(onDismiss:()->Unit,onSave:(SoftwareEntity)->Unit){var maker by remember{mutableStateOf("")};var model by remember{mutableStateOf("")};var category by remember{mutableStateOf("Productivity")};SimpleEditor("Add software",onDismiss,{onSave(SoftwareEntity(name=maker,version=model,category=category,platform="Windows",verificationStatus=VerificationStatus.UNVERIFIED))},maker,model,{maker=it},{model=it},"Name","Version"){OutlinedTextField(category,{category=it},label={Text("Category")})}}
@Composable private fun RequirementEditor(software:SoftwareEntity,onDismiss:()->Unit,onSave:(RequirementEntity)->Unit){var type by remember{mutableStateOf(RequirementType.MINIMUM)};var ram by remember{mutableStateOf("")};var storage by remember{mutableStateOf("")};var cpu by remember{mutableStateOf("")};var gpu by remember{mutableStateOf("")};AlertDialog(onDismissRequest=onDismiss,title={Text("${software.name} ${software.version}")},text={Column{Selector("Requirement type",RequirementType.entries,type,{it.name}){type=it};OutlinedTextField(ram,{ram=it.filter(Char::isDigit)},label={Text("RAM GB")});OutlinedTextField(storage,{storage=it.filter(Char::isDigit)},label={Text("Storage GB")});OutlinedTextField(cpu,{cpu=it.filter(Char::isDigit)},label={Text("Internal CPU tier 1–7")});OutlinedTextField(gpu,{gpu=it.filter(Char::isDigit)},label={Text("Internal GPU tier 1–7")});Text("New records remain unverified until checked against the official publisher source.",style=MaterialTheme.typography.labelSmall)}},confirmButton={Button({onSave(RequirementEntity(softwareId=software.id,type=type,minimumRamGB=ram.toIntOrNull(),minimumStorageGB=storage.toIntOrNull(),minimumCpuTier=cpu.toIntOrNull(),minimumGpuTier=gpu.toIntOrNull(),notes="Needs official verification",verificationStatus=VerificationStatus.UNVERIFIED))}){Text("Save")}},dismissButton={TextButton(onDismiss){Text("Cancel")}})}
@Composable private fun SimpleEditor(title:String,onDismiss:()->Unit,onSave:()->Unit,first:String,second:String,setFirst:(String)->Unit,setSecond:(String)->Unit,firstLabel:String="Manufacturer",secondLabel:String="Model",extra:@Composable ColumnScope.()->Unit){AlertDialog(onDismissRequest=onDismiss,title={Text(title)},text={Column{OutlinedTextField(first,setFirst,label={Text(firstLabel)});OutlinedTextField(second,setSecond,label={Text(secondLabel)});extra()}},confirmButton={Button(onSave,enabled=first.isNotBlank()&&second.isNotBlank()){Text("Save")}},dismissButton={TextButton(onDismiss){Text("Cancel")}})}
